export const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 14",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 14 (128 GB) - Blue',
      price: '89999',
    },
    {
      id: 5,
      category: 'laptops',
      title: "Xiaomi Notebook Pro",
      imgSrc: 'https://m.media-amazon.com/images/I/71iiXU7HHkL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Xiaomi Notebook Pro QHD+IPS AntiGlare Display Intel Core i5-11300H 11th Gen 14 inch(35.56 cm)',
      price: '49999',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Xiaomi Pad 6",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870| ',
      price: '29999',
    },
    {
      id: 12,
      category: 'laptops',
      title: "Samsung Galaxy Book3",
      imgSrc: 'https://m.media-amazon.com/images/I/71ohNusGIjL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Samsung Galaxy Book3 Intel Core i3 13th Gen 1315U 39.6cm (15.6-inch)',
      price: '39,899',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Apple iPhone 11",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Apple iPhone 11 (64GB) - White',
      price: '79999',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro AMOLED",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey with Precision Pen 3',
      price: '19999',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "Apple iPhone 13",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 13 (128GB) - Blue',
      price: '69999',
    },
    {
      id: 13,
      category: 'tablets',
      title: "Samsung Galaxy Tab S9 FE+",
      imgSrc: 'https://m.media-amazon.com/images/I/61l5a94VKkL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Samsung Galaxy Tab S9 FE+ 31.50 cm (12.4 inch) Display, RAM 8 GB, ROM 128 GB Expandable, S Pen in-Box, Wi-Fi, IP68 Tablet, Gray ',
      price: '34499',
    },
    {
      id: 4,
      category: 'laptops',
      title: "Lenovo IdeaPad Slim 5 ",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
      price: '29999',
    },    
    {
      id: 10,
      category: 'mobiles',
      title: "Apple iPhone 15",
      imgSrc: 'https://m.media-amazon.com/images/I/71657TiFeHL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 15 (128 GB) - Black',
      price: '69999',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)',
      price: '49999',
    },
    {
      id: 15,
      category: 'laptops',
      title: "HP Omen Gaming Laptop",
      imgSrc: 'https://m.media-amazon.com/images/I/61ZW4kl+fBL._SL1000_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'HP Omen Gaming Laptop 14Th Gen Intel Core I7-14650Hx,Windows 11 Home 8Gb RTX 4060 Gpu,16.1-Inch(40.9 Cm)',
      price: '133999',
    },
    {
      id: 14,
      category: 'tablets',
      title: "Apple iPad Pro 11″ (M4)",
      imgSrc: 'https://m.media-amazon.com/images/I/61G6WfvA9vL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Apple iPad Pro 11″ (M4) Ultra Retina XDR Display, 256GB, All-Day Battery Life, Standard Glass — Space Black ',
      price: '184999',
    },
    {
      id: 8,
      category: 'laptops',
      title: "Apple MacBook Air Laptop",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
      price: '89999',
    },
    {
      id: 11,
      category: 'mobiles',
      title: "Apple iPhone 16 Pro Max",
      imgSrc: 'https://m.media-amazon.com/images/I/619oqSJVY5L._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Apple iPhone 16 Pro Max (1 TB) - Black Titanium',
      price: '184999',
    },
  ]